-- MySQL Script generated by MySQL Workbench
-- Tue Sep 24 21:03:39 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Tbl_TipoCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tbl_TipoCliente` (
  `KidTipoCliente` INT NOT NULL,
  `tipo_tipocliente` VARCHAR(45) NULL,
  `descripcion_tipocliente` VARCHAR(45) NULL,
  PRIMARY KEY (`KidTipoCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tbl_Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tbl_Cliente` (
  `KidCliente` INT NOT NULL,
  `nombres_cliente` VARCHAR(45) NULL,
  `apellidos_cliente` VARCHAR(45) NULL,
  `edad_cliente` VARCHAR(45) NULL,
  `genero_cliente` TINYINT NULL,
  `tel_cliente` VARCHAR(10) NULL,
  `dpi_cliente` INT NULL,
  `nit_cliente` VARCHAR(10) NULL,
  `KidTipoCliente` INT NOT NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`KidCliente`),
  CONSTRAINT `fk_Cliente_TipoCliente`
    FOREIGN KEY (`KidTipoCliente`)
    REFERENCES `mydb`.`Tbl_TipoCliente` (`KidTipoCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tbl_Empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tbl_Empleados` (
  `KidEmpleados` INT NOT NULL,
  `nombres_empleados` VARCHAR(45) NULL,
  `apellidos_empleados` VARCHAR(45) NULL,
  `genero_empleados` TINYINT NULL,
  `tel_empleados` VARCHAR(10) NULL,
  `dpi_empleados` INT NULL,
  `nit_empleados` VARCHAR(10) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`KidEmpleados`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tbl_Serie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tbl_Serie` (
  `KidSerie` INT NOT NULL,
  `serie_serie` VARCHAR(45) NULL,
  `descripcion_serie` VARCHAR(45) NULL,
  PRIMARY KEY (`KidSerie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tbl_TipoFactura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tbl_TipoFactura` (
  `KidTipoFactura` INT NOT NULL,
  `tipo_tipofactura` VARCHAR(45) NULL,
  `descripcion_tipofactura` VARCHAR(45) NULL,
  PRIMARY KEY (`KidTipoFactura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tbl_FacturaEncabezado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tbl_FacturaEncabezado` (
  `KidFacturaEncabezado` INT NOT NULL,
  `fecha_facturaencabezado` DATE NULL,
  `descripcion_facturaencabezado` VARCHAR(45) NULL,
  `KidSerie` INT NOT NULL,
  `KidTipoFactura` INT NOT NULL,
  `KidCliente` INT NOT NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`KidFacturaEncabezado`, `KidSerie`, `KidTipoFactura`),
  CONSTRAINT `fk_FacturaEncabezado_Cliente1`
    FOREIGN KEY (`KidCliente`)
    REFERENCES `mydb`.`Tbl_Cliente` (`KidCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FacturaEncabezado_Serie1`
    FOREIGN KEY (`KidSerie`)
    REFERENCES `mydb`.`Tbl_Serie` (`KidSerie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FacturaEncabezado_TipoFactura1`
    FOREIGN KEY (`KidTipoFactura`)
    REFERENCES `mydb`.`Tbl_TipoFactura` (`KidTipoFactura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tbl_SolicitudRembolso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tbl_SolicitudRembolso` (
  `KidSolicitudRembolso` INT NOT NULL,
  `fecha_solicitudrembolso` DATE NULL,
  `motivo_solicitudrembolso` VARCHAR(45) NULL,
  `KidFacturaEncabezado` INT NOT NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`KidSolicitudRembolso`),
  CONSTRAINT `fk_SolicitudRembolso_FacturaEncabezado1`
    FOREIGN KEY (`KidFacturaEncabezado`)
    REFERENCES `mydb`.`Tbl_FacturaEncabezado` (`KidFacturaEncabezado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tbl_Devoluciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tbl_Devoluciones` (
  `kidDevoluciones` INT NOT NULL,
  `motivo_devoluciones` VARCHAR(45) NULL,
  `fecha_devoluciones` DATE NULL,
  `KidFacturaEncabezado` INT NOT NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`kidDevoluciones`),
  CONSTRAINT `fk_Devoluciones_FacturaEncabezado1`
    FOREIGN KEY (`KidFacturaEncabezado`)
    REFERENCES `mydb`.`Tbl_FacturaEncabezado` (`KidFacturaEncabezado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tbl_TipoProducto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tbl_TipoProducto` (
  `KidTipoProducto` INT NOT NULL,
  `tipo_tipoproducto` VARCHAR(45) NULL,
  `descripcion_tipoproducto` VARCHAR(45) NULL,
  PRIMARY KEY (`KidTipoProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tbl_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tbl_Producto` (
  `KidProducto` INT NOT NULL,
  `nombre_producto` VARCHAR(45) NULL,
  `descripcion_producto` VARCHAR(45) NULL,
  `KidTipoProducto` INT NOT NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`KidProducto`),
  CONSTRAINT `fk_Producto_TipoProducto1`
    FOREIGN KEY (`KidTipoProducto`)
    REFERENCES `mydb`.`Tbl_TipoProducto` (`KidTipoProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tbl_FacturaDetalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tbl_FacturaDetalle` (
  `KidFacturaDetalle` INT NOT NULL,
  `cantidad_facturadetalle` INT NULL,
  `monto_facturadetalle` DOUBLE NULL,
  `KidProducto` INT NOT NULL,
  `KidFacturaEncabezado` INT NOT NULL,
  PRIMARY KEY (`KidFacturaDetalle`),
  CONSTRAINT `fk_FacturaDetalle_Producto1`
    FOREIGN KEY (`KidProducto`)
    REFERENCES `mydb`.`Tbl_Producto` (`KidProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FacturaDetalle_FacturaEncabezado1`
    FOREIGN KEY (`KidFacturaEncabezado`)
    REFERENCES `mydb`.`Tbl_FacturaEncabezado` (`KidFacturaEncabezado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tbl_Inventario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tbl_Inventario` (
  `KidInventario` INT NOT NULL,
  `fecha_inventario` DATE NULL,
  `cantidad_inventario` INT NULL,
  `KidProducto` INT NOT NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`KidInventario`),
  CONSTRAINT `fk_Inventario_Producto1`
    FOREIGN KEY (`KidProducto`)
    REFERENCES `mydb`.`Tbl_Producto` (`KidProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tbl_Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tbl_Ventas` (
  `KidVentas` INT NOT NULL,
  `descripcion_ventas` VARCHAR(45) NULL,
  `fecha_ventas` DATE NULL,
  `monto_ventas` DOUBLE NULL,
  `KidFacturaEncabezado` INT NOT NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`KidVentas`),
  CONSTRAINT `fk_Ventas_FacturaEncabezado1`
    FOREIGN KEY (`KidFacturaEncabezado`)
    REFERENCES `mydb`.`Tbl_FacturaEncabezado` (`KidFacturaEncabezado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tbl_TipoPago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tbl_TipoPago` (
  `KidTipoPago` INT NOT NULL,
  `tipo_tipopago` VARCHAR(45) NULL,
  `descripcion_tipopago` VARCHAR(45) NULL,
  PRIMARY KEY (`KidTipoPago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tbl_Pagos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tbl_Pagos` (
  `KidPagos` INT NOT NULL,
  `fecha_pagos` DATE NULL,
  `descripcion_pagos` VARCHAR(45) NULL,
  `monto_pagos` DOUBLE NULL,
  `KidTipoPago` INT NOT NULL,
  `KidFacturaEncabezado` INT NOT NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`KidPagos`, `KidTipoPago`),
  CONSTRAINT `fk_Pagos_TipoPago1`
    FOREIGN KEY (`KidTipoPago`)
    REFERENCES `mydb`.`Tbl_TipoPago` (`KidTipoPago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pagos_FacturaEncabezado1`
    FOREIGN KEY (`KidFacturaEncabezado`)
    REFERENCES `mydb`.`Tbl_FacturaEncabezado` (`KidFacturaEncabezado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tbl_Comisiones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tbl_Comisiones` (
  `KidComisiones` INT NOT NULL,
  `fecha_comisiones` DATE NULL,
  `descripcion_comisiones` VARCHAR(45) NULL,
  `monto_comisiones` DOUBLE NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`KidComisiones`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tbl_Asignacion_Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tbl_Asignacion_Empleado` (
  `KidVentas` INT NOT NULL,
  `KidComisiones` INT NOT NULL,
  `KidEmpleados` INT NOT NULL,
  PRIMARY KEY (`KidVentas`, `KidComisiones`),
  CONSTRAINT `fk_Ventas_has_Comisiones_Ventas1`
    FOREIGN KEY (`KidVentas`)
    REFERENCES `mydb`.`Tbl_Ventas` (`KidVentas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ventas_has_Comisiones_Comisiones1`
    FOREIGN KEY (`KidComisiones`)
    REFERENCES `mydb`.`Tbl_Comisiones` (`KidComisiones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Asignacion_Empleado_Empleados1`
    FOREIGN KEY (`KidEmpleados`)
    REFERENCES `mydb`.`Tbl_Empleados` (`KidEmpleados`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tbl_Precios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tbl_Precios` (
  `KidPrecios` INT NOT NULL,
  `precio_precios` DOUBLE NULL,
  `descripcion_precios` VARCHAR(45) NULL,
  `KidProducto` INT NOT NULL,
  PRIMARY KEY (`KidPrecios`),
  CONSTRAINT `fk_Precios_Producto1`
    FOREIGN KEY (`KidProducto`)
    REFERENCES `mydb`.`Tbl_Producto` (`KidProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
